// Require Node modules
const inquirer = require("inquirer");
const fs = require("fs");
const jest = require("jest");
// Require lib modules
const Employee = require("./lib/Employee");
const Engineer = require("./lib/Engineer");
const Intern = require("./lib/Intern");
const Manager = require("./lib/Manager");
